# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute probas over slices
#'
#' @param df a DataFrame of species pairs
#' @param mat a species matrix
#'
get_probaC <- function(df, mat) {
    .Call(`_FastCooccur_get_probaC`, df, mat)
}

